### ISSUE TITLE
Get data": [], when directly calling /data/v1/get/C/A/HS endpoint 

### ISSUE THREAD

**Issue by veptune** [uncomtrade/comtradeapicall#18]
Hell all,

I don't see any forum where I can report my issue so I try here sorry.

Before I use this package, I want try API request directly with Postman.

I use this request to get trade data for Canada (ID : 134) :

https://comtradeapi.un.org/data/v1/get/C/A/HS?reporterCode=124&period=202001&flowCode=-1&motCode=1000

But what I got is (the result is the same in Postman or when I use their "Try it" button on https://comtradedeveloper.un.org/api-details#api=comtrade-v1&operation=get-get):

{
    "elapsedTime": "0.09 secs",
    "count": 0,
    "data": [],
    "error": ""
}

What am I missing?

Also, I can't find anywhere in their doc the reference for the Flow Code parameter (X, M, XQP...)

Do you know where I can post my question (there is no "comtrade" on stackoverflow)

Thanks

**Comment by uncomtrade** [comment]
The passed parameter values are incorrect:
- When requesting Annual data the period should be formatted as YYYY, when requesting Monthly data the period should be formatted as YYYYMM
- There is no valid value -1 for parameter flowCode. To review the list of references please visit https://comtradeplus.un.org/ListOfReferences
